### ISSUE TITLE
Add base HTML contact page:

### ISSUE THREAD

**Issue by dgustave** [asmvm/Public_Health_Website#7]
1. Add Html from landing page. 
2. Have emergency contact hotlines information
3. Plan wire frame for forms and visualize the page.
4. Add Dropdown menu for type of inquiry. 
5. Row of information for social media. 
6. Row Trending Stories and Learn about us

- High school students need hotline numbers as well as the community
- Focus on Mental Health and the Georgia Community for now
- Ask about the core Assistance programs

**Comment by asmvm** [comment]
Alvaro to follow up with Katie and Megan about types of contact information. Good to continue building out the full features of the page.

**Comment by dgustave** [comment]
The main part of the website is done. Continued to backend and the final will be styling!
